// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities.Configurations
{
    public partial class AppEventConfiguration : IEntityTypeConfiguration<AppEvent>
    {
        public void Configure(EntityTypeBuilder<AppEvent> entity)
        {
            entity.Property(x => x.Id)
                              .HasColumnName("EventId");

            entity.HasKey(e => e.Id).HasName("PK__AppEvent__7944C810F5EE2443");

            entity.ToTable(tb => tb.HasTrigger("trigger_AppEvents_AU"));

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.EventName).IsUnicode(false);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AppEvent> entity);
    }
}
