// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities.Configurations
{
    public partial class ClaimsAuConfiguration : IEntityTypeConfiguration<ClaimsAu>
    {
        public void Configure(EntityTypeBuilder<ClaimsAu> entity)
        {
            entity.Property(x => x.Id)
                .HasColumnName("HistoryRowId");

            entity.HasKey(e => e.Id).HasName("PK__Claims_A__5F3896387C46B954");

            entity.ToTable("Claims_AU");

            entity.Property(e => e.AllowedAmount).HasColumnType("money");
            entity.Property(e => e.ClaimNumber)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Currency)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.DisallowAmount).HasColumnType("money");
            entity.Property(e => e.HistoryCreatedDate).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.OtherChargesAmount).HasColumnType("money");
            entity.Property(e => e.PaidDate).HasColumnType("datetime");
            entity.Property(e => e.RequestedOn).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.CropInsurance).WithMany(p => p.ClaimsAus)
                .HasForeignKey(d => d.CropInsuranceId)
                .HasConstraintName("FK_CropInsurances_Claims_AU");

            entity.HasOne(d => d.CropInsurancePremium).WithMany(p => p.ClaimsAus)
                .HasForeignKey(d => d.CropInsurancePremiumId)
                .HasConstraintName("FK_CropInsurancePremiums_Claims_AU");

            entity.HasOne(d => d.Farmer).WithMany(p => p.ClaimsAus)
                .HasForeignKey(d => d.FarmerId)
                .HasConstraintName("FK_Farmers_Claims_AU");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClaimsAu> entity);
    }
}
