// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities.Configurations
{
    public partial class CropInsurancePremiumsAuConfiguration : IEntityTypeConfiguration<CropInsurancePremiumsAu>
    {
        public void Configure(EntityTypeBuilder<CropInsurancePremiumsAu> entity)
        {
            entity.Property(x => x.Id)
              .HasColumnName("HistoryRowId");

            entity.HasKey(e => e.Id).HasName("PK__CropInsu__5F3896381AF0D3F9");

            entity.ToTable("CropInsurancePremiums_AU");

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.HistoryCreatedDate).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.HasOne(d => d.CropInsurance).WithMany(p => p.CropInsurancePremiumsAus)
                .HasForeignKey(d => d.CropInsuranceId)
                .HasConstraintName("FK_CropInsurance_CropInsurancePremiums_AU");

            entity.HasOne(d => d.InsurancePremium).WithMany(p => p.CropInsurancePremiumsAus)
                .HasForeignKey(d => d.InsurancePremiumId)
                .HasConstraintName("FK_InsurancePremium_CropInsurancePremiums_AU");

            entity.HasOne(d => d.PremiumFrequency).WithMany(p => p.CropInsurancePremiumsAus)
                .HasForeignKey(d => d.PremiumFrequencyId)
                .HasConstraintName("FK_PremiumFrequency_CropInsurancePremiums_AU");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CropInsurancePremiumsAu> entity);
    }
}
