// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities.Configurations
{
    public partial class CropCategoryConfiguration : IEntityTypeConfiguration<CropCategory>
    {
        public void Configure(EntityTypeBuilder<CropCategory> entity)
        {
            entity.Property(x => x.Id)
                           .HasColumnName("CropCategoryId");

            entity.HasKey(e => e.Id).HasName("PK__CropCate__EA6546C4C67F2FE7");

            entity.ToTable(tb => tb.HasTrigger("trigger_CropCategories_AU"));

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.CropCategoryName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CropCategory> entity);
    }
}
