// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities.Configurations
{
    public partial class EmailTemplatesAuConfiguration : IEntityTypeConfiguration<EmailTemplatesAu>
    {
        public void Configure(EntityTypeBuilder<EmailTemplatesAu> entity)
        {
            entity.Property(x => x.Id)
                  .HasColumnName("HistoryRowId");

            entity.HasKey(e => e.Id).HasName("PK__EmailTemplates__TemplateId_AU");

            entity.ToTable("EmailTemplates_AU");

            entity.Property(e => e.Bcc).IsUnicode(false);
            entity.Property(e => e.Cc).IsUnicode(false);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.HistoryCreatedDate).HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MailContent)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.MailSubject)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.MailTo)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Event).WithMany(p => p.EmailTemplatesAus)
                .HasForeignKey(d => d.EventId)
                .HasConstraintName("FK__EmailTemplates__EventId_AU");

            entity.HasOne(d => d.Role).WithMany(p => p.EmailTemplatesAus)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK_EmailTemplates_RoleId_AU");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EmailTemplatesAu> entity);
    }
}
