// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities.Configurations
{
    public partial class EmailTemplateConfiguration : IEntityTypeConfiguration<EmailTemplate>
    {
        public void Configure(EntityTypeBuilder<EmailTemplate> entity)
        {
            entity.Property(x => x.Id)
                             .HasColumnName("TemplateId");

            entity.HasKey(e => e.Id).HasName("PK__EmailTemplates__TemplateId");

            entity.ToTable(tb => tb.HasTrigger("trigger_EmailTemplates_AU"));

            entity.Property(e => e.Bcc).IsUnicode(false);
            entity.Property(e => e.Cc).IsUnicode(false);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MailContent)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.MailSubject)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.MailTo)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Event).WithMany(p => p.EmailTemplates)
                .HasForeignKey(d => d.EventId)
                .HasConstraintName("FK__EmailTemplates__EventId");

            entity.HasOne(d => d.Role).WithMany(p => p.EmailTemplates)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK_EmailTemplates_RoleId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EmailTemplate> entity);
    }
}
