// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities.Configurations
{
    public partial class FarmerCropsAuConfiguration : IEntityTypeConfiguration<FarmerCropsAu>
    {
        public void Configure(EntityTypeBuilder<FarmerCropsAu> entity)
        {
            entity.Property(x => x.Id)
              .HasColumnName("HistoryRowId");
            entity.HasKey(e => e.Id).HasName("PK__FarmerAUCr__56CFA48E155F5C1D");

            entity.ToTable("FarmerCrops_AU");

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.CultEndDate).HasColumnType("datetime");
            entity.Property(e => e.CultStartDate).HasColumnType("datetime");
            entity.Property(e => e.ESusPoints).HasColumnName("eSusPoints");
            entity.Property(e => e.FarmLandSize).HasColumnType("decimal(10, 5)");
            entity.Property(e => e.HarvestingEndDate).HasColumnType("datetime");
            entity.Property(e => e.HarvestingStartDate).HasColumnType("datetime");
            entity.Property(e => e.HistoryCreatedDate).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PlantGrowthEndDate).HasColumnType("datetime");
            entity.Property(e => e.PlantGrowthStartDate).HasColumnType("datetime");
            entity.Property(e => e.PreCultEndDate).HasColumnType("datetime");
            entity.Property(e => e.PreCultStartDate).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FarmerCropsAu> entity);
    }
}
