// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities.Configurations
{
    public partial class FarmerCropConfiguration : IEntityTypeConfiguration<FarmerCrop>
    {
        public void Configure(EntityTypeBuilder<FarmerCrop> entity)
        {
            entity.Property(x => x.Id)
                         .HasColumnName("FarmerCropId");

            entity.HasKey(e => e.Id).HasName("PK__FarmerCr__56CFA48E155F5C1D");

            entity.ToTable(tb => tb.HasTrigger("trigger_FarmerCrops_AU"));

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.CultEndDate).HasColumnType("datetime");
            entity.Property(e => e.CultStartDate).HasColumnType("datetime");
            entity.Property(e => e.ESusPoints).HasColumnName("eSusPoints");
            entity.Property(e => e.FarmLandSize).HasColumnType("decimal(10, 5)");
            entity.Property(e => e.HarvestingEndDate).HasColumnType("datetime");
            entity.Property(e => e.HarvestingStartDate).HasColumnType("datetime");
            entity.Property(e => e.IsHarvestCompleted).HasDefaultValue(false);
            entity.Property(e => e.IsPlantGrowthCompleted).HasDefaultValue(false);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PlantGrowthEndDate).HasColumnType("datetime");
            entity.Property(e => e.PlantGrowthStartDate).HasColumnType("datetime");
            entity.Property(e => e.PreCultEndDate).HasColumnType("datetime");
            entity.Property(e => e.PreCultStartDate).HasColumnType("datetime");

            entity.HasOne(d => d.Crop).WithMany(p => p.FarmerCrops)
                .HasForeignKey(d => d.CropId)
                .HasConstraintName("FK__FarmerCro__CropI__08B54D69");

            entity.HasOne(d => d.Farmer).WithMany(p => p.FarmerCrops)
                .HasForeignKey(d => d.FarmerId)
                .HasConstraintName("FK__FarmerCro__Farme__07C12930");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FarmerCrop> entity);
    }
}
