// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities.Configurations
{
    public partial class InsurancePoliciesAuConfiguration : IEntityTypeConfiguration<InsurancePoliciesAu>
    {
        public void Configure(EntityTypeBuilder<InsurancePoliciesAu> entity)
        {
            entity.Property(x => x.Id)
             .HasColumnName("HistoryRowId");

            entity.HasKey(e => e.Id).HasName("PK__Insuranc__5F3896386A160592");

            entity.ToTable("InsurancePolicies_AU");

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.HistoryCreatedDate).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PolicyName)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.PolicyNumber)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.InsuranceProvider).WithMany(p => p.InsurancePoliciesAus)
                .HasForeignKey(d => d.InsuranceProviderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InsuranceProviders_InsurancePolicy_AU");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InsurancePoliciesAu> entity);
    }
}
