// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities.Configurations
{
    public partial class InsuranceProviderDocumentConfiguration : IEntityTypeConfiguration<InsuranceProviderDocument>
    {
        public void Configure(EntityTypeBuilder<InsuranceProviderDocument> entity)
        {
            entity.Property(x => x.Id)
                            .HasColumnName("InsuranceProviderDocumentId");

            entity.HasKey(e => e.Id).HasName("PK__Insuranc__AE9929CD8975B86D");

            entity.ToTable(tb => tb.HasTrigger("trigger_InsuranceProviderDocuments_AU"));

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.DocumentName)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.DocumentPath).IsUnicode(false);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Insurer).WithMany(p => p.InsuranceProviderDocuments)
                .HasForeignKey(d => d.InsurerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InsuranceProviders_InsuranceProviderDocuments");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InsuranceProviderDocument> entity);
    }
}
