// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities.Configurations
{
    public partial class InsurerUserConfiguration : IEntityTypeConfiguration<InsurerUser>
    {
        public void Configure(EntityTypeBuilder<InsurerUser> entity)
        {
            entity.Property(x => x.Id)
                           .HasColumnName("InsurerUserId");

            entity.HasKey(e => e.Id).HasName("PK__InsurerU__68754BA822ABDB9E");

            entity.ToTable(tb => tb.HasTrigger("trigger_InsurerUsers_AU"));

            entity.Property(e => e.ContactNumber).HasColumnType("numeric(15, 0)");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.EmailId)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Gender)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Insurer).WithMany(p => p.InsurerUsers)
                .HasForeignKey(d => d.InsurerId)
                .HasConstraintName("FK_InsuranceProviders_InsurerUsers");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InsurerUser> entity);
    }
}
