// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities.Configurations
{
    public partial class LocationsAuConfiguration : IEntityTypeConfiguration<LocationsAu>
    {
        public void Configure(EntityTypeBuilder<LocationsAu> entity)
        {
            entity.Property(x => x.Id)
                  .HasColumnName("HistoryRowId");

            entity.HasKey(e => e.Id).HasName("PK__Location__5F3896384816BFE7");

            entity.ToTable("Locations_AU");

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.HistoryCreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Latitude)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.LocationName)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Longitude)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.HasOne(d => d.District).WithMany(p => p.LocationsAus)
                .HasForeignKey(d => d.DistrictId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Districts_Locations_AU");

            entity.HasOne(d => d.Region).WithMany(p => p.LocationsAus)
                .HasForeignKey(d => d.RegionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Regions_Locations_AU");

            entity.HasOne(d => d.SubCounty).WithMany(p => p.LocationsAus)
                .HasForeignKey(d => d.SubCountyId)
                .HasConstraintName("FK_SubCounties_Locations_AU");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LocationsAu> entity);
    }
}
