// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities.Configurations
{
    public partial class RoleFeaturesAuConfiguration : IEntityTypeConfiguration<RoleFeaturesAu>
    {
        public void Configure(EntityTypeBuilder<RoleFeaturesAu> entity)
        {
            entity.Property(x => x.Id)
          .HasColumnName("HistoryRowId");

            entity.HasKey(e => e.Id).HasName("PK__RoleFeat__5F38963886865695");

            entity.ToTable("RoleFeatures_AU");

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.HistoryCreatedDate).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Feature).WithMany(p => p.RoleFeaturesAus)
                .HasForeignKey(d => d.FeatureId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Roles_Features_AU");

            entity.HasOne(d => d.Role).WithMany(p => p.RoleFeaturesAus)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Roles_RoleFunctionalities_AU");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RoleFeaturesAu> entity);
    }
}
