// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities.Configurations
{
    public partial class RoleFeatureConfiguration : IEntityTypeConfiguration<RoleFeature>
    {
        public void Configure(EntityTypeBuilder<RoleFeature> entity)
        {
            entity.Property(x => x.Id)
           .HasColumnName("RoleFeatureId");

            entity.HasKey(e => e.Id).HasName("PK__RoleFeat__0CA024417FDE3A5F");

            entity.ToTable(tb => tb.HasTrigger("trigger_RoleFeatures_AU"));

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Feature).WithMany(p => p.RoleFeatures)
                .HasForeignKey(d => d.FeatureId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Roles_Features");

            entity.HasOne(d => d.Role).WithMany(p => p.RoleFeatures)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Roles_RoleFunctionalities");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RoleFeature> entity);
    }
}
