// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities.Configurations
{
    public partial class RoleSubFunctionalityConfiguration : IEntityTypeConfiguration<RoleSubFunctionality>
    {
        public void Configure(EntityTypeBuilder<RoleSubFunctionality> entity)
        {
            entity.Property(x => x.Id)
                  .HasColumnName("RoleSubFunctionalityId");

            entity.HasKey(e => e.Id).HasName("PK__RoleSubF__6EC696773AEAF78C");

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.SubFunctionality)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.HasOne(d => d.RoleFunctionality).WithMany(p => p.RoleSubFunctionalities)
                .HasForeignKey(d => d.RoleFunctionalityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RoleFunctionalities");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RoleSubFunctionality> entity);
    }
}
