// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities.Configurations
{
    public partial class RoleFunctionalitiesAuConfiguration : IEntityTypeConfiguration<RoleFunctionalitiesAu>
    {
        public void Configure(EntityTypeBuilder<RoleFunctionalitiesAu> entity)
        {
            entity.Property(x => x.Id)
                  .HasColumnName("HistoryRowId");

            entity.HasKey(e => e.Id).HasName("PK__RoleFunc__5F389638F3336860");

            entity.ToTable("RoleFunctionalities_AU");

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Feature)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Functionality)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.HistoryCreatedDate).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Role).WithMany(p => p.RoleFunctionalitiesAus)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Roles_RoleFunctionalities_AU");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RoleFunctionalitiesAu> entity);
    }
}
