// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities.Configurations
{
    public partial class SeasonsAuConfiguration : IEntityTypeConfiguration<SeasonsAu>
    {
        public void Configure(EntityTypeBuilder<SeasonsAu> entity)
        {
            entity.Property(x => x.Id)
                  .HasColumnName("HistoryRowId");

            entity.HasKey(e => e.Id).HasName("PK__Seasons___5F389638ECE6FDC1");

            entity.ToTable("Seasons_AU");

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.HistoryCreatedDate).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.SeasonName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.StartDate).HasColumnType("datetime");

            entity.HasOne(d => d.Location).WithMany(p => p.SeasonsAus)
                .HasForeignKey(d => d.LocationId)
                .HasConstraintName("FK_Locations_Seasons_AU");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SeasonsAu> entity);
    }
}
