// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities.Configurations
{
    public partial class SubCountyConfiguration : IEntityTypeConfiguration<SubCounty>
    {
        public void Configure(EntityTypeBuilder<SubCounty> entity)
        {
            entity.Property(x => x.Id)
                             .HasColumnName("SubCountyId");

            entity.HasKey(e => e.Id).HasName("PK__SubCount__11B0FF6F27F77664");

            entity.ToTable(tb => tb.HasTrigger("trigger_SubCounties_AU"));

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.SubCountyName)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.HasOne(d => d.District).WithMany(p => p.SubCounties)
                .HasForeignKey(d => d.DistrictId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Districts_SubCounties");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SubCounty> entity);
    }
}
