// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities.Configurations
{
    public partial class UsersAuConfiguration : IEntityTypeConfiguration<UsersAu>
    {
        public void Configure(EntityTypeBuilder<UsersAu> entity)
        {
            entity.Property(x => x.Id)
                             .HasColumnName("HistoryRowId");

            entity.HasKey(e => e.Id).HasName("PK__Users_AU__5F38963819D471A3");

            entity.ToTable("Users_AU");

            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.HistoryCreatedDate).HasColumnType("datetime");
            entity.Property(e => e.LastLoggedInDate).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Otp)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.OtpExipiryTime).HasColumnType("datetime");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.PasswordSalt)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.ProfilePicture)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.RefreshToken).IsUnicode(false);
            entity.Property(e => e.RefreshTokenExpiryTime)
                .HasColumnType("datetime")
                .HasColumnName("RefreshTokenExpiryTime ");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.InsurerUser).WithMany(p => p.UsersAus)
                .HasForeignKey(d => d.InsurerUserId)
                .HasConstraintName("FK_InsurerUsers_Users_AU");

            entity.HasOne(d => d.UserType).WithMany(p => p.UsersAus)
                .HasForeignKey(d => d.UserTypeId)
                .HasConstraintName("FK_UserTypes_Users_AU");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UsersAu> entity);
    }
}
