os: Visual Studio 2022
version: 1.0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: 1Cn22xLzXzP6P3dTXXJX0G3bcsluYI9GG
matrix:
  allow_failures:
    - CLI_VERSION: Latest
before_build:
  - nuget restore ".\eSusInsurers.sln"
build:
  project: eSusInsurers.sln
  verbosity: minimal
test_script:
- ps: >-
    OpenCover.Console.exe -register:user -target:xunit.console.clr4.exe "-targetargs:""src\eSusInsurers.Tests\bin\$env:CONFIGURATION\eSusInsurers.Tests.dll"" /noshadow /appveyor" -filter:"+[eSusInsurers*]*" -output:opencoverCoverage.xml

    $coveralls = (Resolve-Path "coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()

    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
