os: Visual Studio 2022
version: 1.0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  matrix:
    - CLI_VERSION: 1.0.0-beta-002071
    - CLI_VERSION: Latest
  COVERALLS_REPO_TOKEN:
    secure: 1Cn22xLzXzP6P3dTXXJX0G3bcsluYI9GG
matrix:
  allow_failures:
    - CLI_VERSION: Latest
install:
  - ps: .\scripts\show-dotnet-info.ps1
  # Download install script to install .NET cli in .dotnet dir
  - ps: mkdir -Force ".\scripts\obtain\" | Out-Null
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/install.ps1" -OutFile ".\scripts\obtain\install.ps1"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: '& .\scripts\obtain\install.ps1 -Channel "preview" -version "$env:CLI_VERSION" -InstallDir "$env:DOTNET_INSTALL_DIR" -NoPath'
  # add dotnet to PATH
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
before_build:
  - nuget restore ".\eSusInsurers.sln"
build:
  project: eSusInsurers.sln
  verbosity: minimal
test_script:
- ps: >-
    .\src\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:xunit.console.clr4.exe "-targetargs:""src\eSusInsurers.Tests\bin\$env:CONFIGURATION\eSusInsurers.Tests.dll"" /noshadow /appveyor" -filter:"+[eSusInsurers*]*" -output:opencoverCoverage.xml

    $coveralls = (Resolve-Path "src/packages/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()

    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
