// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace eSusInsurers.Domain
{
    public partial class eSusInsurerContext
    {
        private IeSusInsurerContextProcedures _procedures;

        public virtual IeSusInsurerContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new eSusInsurerContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IeSusInsurerContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class eSusInsurerContextProcedures : IeSusInsurerContextProcedures
    {
        private readonly eSusInsurerContext _context;

        public eSusInsurerContextProcedures(eSusInsurerContext context)
        {
            _context = context;
        }

        public virtual async Task<List<SP_GetApplicationMenusResult>> SP_GetApplicationMenusAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_GetApplicationMenusResult>("EXEC @returnValue = [dbo].[SP_GetApplicationMenus]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_GetRoleDetailsResult>> SP_GetRoleDetailsAsync(long? RoleId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "RoleId",
                    Value = RoleId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_GetRoleDetailsResult>("EXEC @returnValue = [dbo].[SP_GetRoleDetails] @RoleId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
