// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace eSusInsurers.Domain
{
    public partial interface IeSusInsurerContextProcedures
    {
        Task<List<SP_GetApplicationMenusResult>> SP_GetApplicationMenusAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GetRoleDetailsResult>> SP_GetRoleDetailsAsync(long? RoleId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
