// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class AppEventsAu : BaseAuditableEntity
{
    public DateTime? HistoryCreatedDate { get; set; }

    public int EventId { get; set; }

    public string EventName { get; set; }

    public bool? IsActive { get; set; }
}