// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class CropInsurancePremium : BaseAuditableEntity
{
    public int? CropInsuranceId { get; set; }

    public int? InsurancePremiumId { get; set; }

    public int? PremiumFrequencyId { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Claim> Claims { get; set; } = new List<Claim>();

    public virtual ICollection<ClaimsAu> ClaimsAus { get; set; } = new List<ClaimsAu>();

    public virtual CropInsurance CropInsurance { get; set; }

    public virtual InsurancePremium InsurancePremium { get; set; }

    public virtual InsurancePremiumFrequency PremiumFrequency { get; set; }

    public virtual ICollection<PremiumPayment> PremiumPayments { get; set; } = new List<PremiumPayment>();

    public virtual ICollection<PremiumPaymentsAu> PremiumPaymentsAus { get; set; } = new List<PremiumPaymentsAu>();
}