// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class CropInsurance : BaseAuditableEntity
{
    public int FarmerId { get; set; }

    public int FarmerCropId { get; set; }

    public string CropName { get; set; }

    public decimal? Longitude { get; set; }

    public decimal? Latitude { get; set; }

    public int InsurancePolicyId { get; set; }

    public int InsuranceRiskId { get; set; }

    public string Status { get; set; }

    public string Comments { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Claim> Claims { get; set; } = new List<Claim>();

    public virtual ICollection<ClaimsAu> ClaimsAus { get; set; } = new List<ClaimsAu>();

    public virtual ICollection<CropInsurancePremium> CropInsurancePremia { get; set; } = new List<CropInsurancePremium>();

    public virtual ICollection<CropInsurancePremiumsAu> CropInsurancePremiumsAus { get; set; } = new List<CropInsurancePremiumsAu>();

    public virtual Farmer Farmer { get; set; }

    public virtual FarmerCrop FarmerCrop { get; set; }

    public virtual InsurancePolicy InsurancePolicy { get; set; }

    public virtual InsuranceRisk InsuranceRisk { get; set; }

    public virtual ICollection<PremiumPayment> PremiumPayments { get; set; } = new List<PremiumPayment>();

    public virtual ICollection<PremiumPaymentsAu> PremiumPaymentsAus { get; set; } = new List<PremiumPaymentsAu>();
}