// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class District : BaseAuditableEntity
{
    public string DistrictName { get; set; }

    public int RegionId { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Location> Locations { get; set; } = new List<Location>();

    public virtual ICollection<LocationsAu> LocationsAus { get; set; } = new List<LocationsAu>();

    public virtual Region Region { get; set; }

    public virtual ICollection<SubCounty> SubCounties { get; set; } = new List<SubCounty>();

    public virtual ICollection<SubCountiesAu> SubCountiesAus { get; set; } = new List<SubCountiesAu>();
}