// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class EmailTemplatesAu : BaseAuditableEntity
{
    public DateTime? HistoryCreatedDate { get; set; }

    public int TemplateId { get; set; }

    public int? EventId { get; set; }

    public int? RoleId { get; set; }

    public string MailSubject { get; set; }

    public string MailContent { get; set; }

    public string MailTo { get; set; }

    public string Cc { get; set; }

    public string Bcc { get; set; }

    public bool? IsActive { get; set; }

    public virtual AppEvent Event { get; set; }

    public virtual Role Role { get; set; }
}