// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class FeaturesAu : BaseAuditableEntity
{
    public DateTime HistoryCreatedDate { get; set; }

    public int FeatureId { get; set; }

    public string Feature { get; set; }

    public bool? IsActive { get; set; }
}