// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class Functionality : BaseAuditableEntity
{
    public int FeatureId { get; set; }

    public string Functionality1 { get; set; }

    public bool? IsActive { get; set; }

    public virtual Feature Feature { get; set; }

    public virtual ICollection<SubFunctionality> SubFunctionalities { get; set; } = new List<SubFunctionality>();

    public virtual ICollection<SubFunctionalitiesAu> SubFunctionalitiesAus { get; set; } = new List<SubFunctionalitiesAu>();
}