// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class FunctionalitiesAu : BaseAuditableEntity
{

    public DateTime HistoryCreatedDate { get; set; }

    public int FunctionalityId { get; set; }

    public int FeatureId { get; set; }

    public string Functionality { get; set; }

    public bool? IsActive { get; set; }

    public virtual Feature Feature { get; set; }
}