// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class InsurancePremiumAu : BaseAuditableEntity
{
    public DateTime HistoryCreatedDate { get; set; }

    public int InsurancePremiumId { get; set; }

    public int InsurancePolicyId { get; set; }

    public int? InsuranceRiskId { get; set; }

    public decimal? TotalPremiumAmount { get; set; }

    public decimal? PremiumAmountCurrency { get; set; }

    public decimal? SumInsuredAmount { get; set; }

    public decimal? SumInsuredAmountCurrency { get; set; }

    public bool? IsActive { get; set; }

    public virtual InsurancePolicy InsurancePolicy { get; set; }

    public virtual InsuranceRisk InsuranceRisk { get; set; }
}