// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class InsurancePremiumFrequencyAu : BaseAuditableEntity
{
    public DateTime HistoryCreatedDate { get; set; }

    public int PremiumFrequencyId { get; set; }

    public int InsurancePremiumId { get; set; }

    public string PremiumFrequency { get; set; }

    public bool? IsActive { get; set; }

    public virtual InsurancePremium InsurancePremium { get; set; }
}