// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class InsurancePremium : BaseAuditableEntity
{
    public int InsurancePolicyId { get; set; }

    public int? InsuranceRiskId { get; set; }

    public decimal? TotalPremiumAmount { get; set; }

    public decimal? PremiumAmountCurrency { get; set; }

    public decimal? SumInsuredAmount { get; set; }

    public decimal? SumInsuredAmountCurrency { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<CropInsurancePremium> CropInsurancePremia { get; set; } = new List<CropInsurancePremium>();

    public virtual ICollection<CropInsurancePremiumsAu> CropInsurancePremiumsAus { get; set; } = new List<CropInsurancePremiumsAu>();

    public virtual InsurancePolicy InsurancePolicy { get; set; }

    public virtual ICollection<InsurancePremiumFrequency> InsurancePremiumFrequencies { get; set; } = new List<InsurancePremiumFrequency>();

    public virtual ICollection<InsurancePremiumFrequencyAu> InsurancePremiumFrequencyAus { get; set; } = new List<InsurancePremiumFrequencyAu>();

    public virtual InsuranceRisk InsuranceRisk { get; set; }
}