// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class InsuranceRisk : BaseAuditableEntity
{
    public int InsurancePolicyId { get; set; }

    public int SeasonId { get; set; }

    public int LocationId { get; set; }

    public string CropName { get; set; }

    public decimal? Deductible { get; set; }

    public decimal? DroughtLoss { get; set; }

    public decimal? ExcessRainfallLoss { get; set; }

    public decimal? TotalLoss { get; set; }

    public decimal? Payout { get; set; }

    public decimal? FinalPayout { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<CropInsuranceAu> CropInsuranceAus { get; set; } = new List<CropInsuranceAu>();

    public virtual ICollection<CropInsurance> CropInsurances { get; set; } = new List<CropInsurance>();

    public virtual InsurancePolicy InsurancePolicy { get; set; }

    public virtual ICollection<InsurancePremium> InsurancePremia { get; set; } = new List<InsurancePremium>();

    public virtual ICollection<InsurancePremiumAu> InsurancePremiumAus { get; set; } = new List<InsurancePremiumAu>();

    public virtual Location Location { get; set; }

    public virtual Season Season { get; set; }
}