// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class InsurancePremiumFrequency : BaseAuditableEntity
{
    public int InsurancePremiumId { get; set; }

    public string PremiumFrequency { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<CropInsurancePremium> CropInsurancePremia { get; set; } = new List<CropInsurancePremium>();

    public virtual ICollection<CropInsurancePremiumsAu> CropInsurancePremiumsAus { get; set; } = new List<CropInsurancePremiumsAu>();

    public virtual InsurancePremium InsurancePremium { get; set; }
}