// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class PaymentMode : BaseAuditableEntity
{

    public string PaymentMode1 { get; set; }

    public bool? IsActive { get; set; }

}