// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class RoleSubFunctionality : BaseAuditableEntity
{
    public string SubFunctionality { get; set; }

    public int RoleFunctionalityId { get; set; }

    public bool? IsActive { get; set; }

    public virtual RoleFunctionality RoleFunctionality { get; set; }
}