// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class RoleFunctionality : BaseAuditableEntity
{
    public string Feature { get; set; }

    public string Functionality { get; set; }

    public int RoleId { get; set; }

    public bool? IsActive { get; set; }

    public virtual Role Role { get; set; }

    public virtual ICollection<RoleSubFunctionality> RoleSubFunctionalities { get; set; } = new List<RoleSubFunctionality>();

    public virtual ICollection<RoleSubFunctionalitiesAu> RoleSubFunctionalitiesAus { get; set; } = new List<RoleSubFunctionalitiesAu>();
}