// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class RoleFunctionalitiesAu : BaseAuditableEntity
{
    public DateTime HistoryCreatedDate { get; set; }

    public int RoleFunctionalityId { get; set; }

    public string Feature { get; set; }

    public string Functionality { get; set; }

    public int RoleId { get; set; }

    public bool? IsActive { get; set; }

    public virtual Role Role { get; set; }
}