// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class Role : BaseAuditableEntity
{
    public string RoleName { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<EmailTemplate> EmailTemplates { get; set; } = new List<EmailTemplate>();

    public virtual ICollection<EmailTemplatesAu> EmailTemplatesAus { get; set; } = new List<EmailTemplatesAu>();

    public virtual ICollection<RoleFeature> RoleFeatures { get; set; } = new List<RoleFeature>();

    public virtual ICollection<RoleFeaturesAu> RoleFeaturesAus { get; set; } = new List<RoleFeaturesAu>();
}