// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace eSusInsurers.Domain.Entities
{
    public partial class SP_GetRoleDetailsResult
    {
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public int? ReportingToId { get; set; }
        public string ReportRoleName { get; set; }
        public string ApplicationMenuRolePrivileges { get; set; }
    }
}
