// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class SubCountiesAu : BaseAuditableEntity
{

    public DateTime HistoryCreatedDate { get; set; }

    public int SubCountyId { get; set; }

    public string SubCountyName { get; set; }

    public int DistrictId { get; set; }

    public bool? IsActive { get; set; }

    public virtual District District { get; set; }
}