// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class TaxComponent : BaseAuditableEntity
{
    public string TaxComponent1 { get; set; }

    public int? Value { get; set; }

    public bool? IsActive { get; set; }
}