// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Entities;

public partial class UsersAu : BaseAuditableEntity
{
    public DateTime HistoryCreatedDate { get; set; }

    public int UserId { get; set; }

    public string UserName { get; set; }

    public string PasswordSalt { get; set; }

    public string PasswordHash { get; set; }

    public int? UserTypeId { get; set; }

    public int? InsurerUserId { get; set; }

    public bool IsEnforcePassword { get; set; }

    public DateTime? LastLoggedInDate { get; set; }

    public string ProfilePicture { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenExpiryTime { get; set; }

    public bool? IsActive { get; set; }

    public string Otp { get; set; }

    public DateTime? OtpExipiryTime { get; set; }

    public virtual InsurerUser InsurerUser { get; set; }

    public virtual UserType UserType { get; set; }
}