// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class ApplicationChildMenuConfiguration : IEntityTypeConfiguration<ApplicationChildMenu>
    {
        public void Configure(EntityTypeBuilder<ApplicationChildMenu> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Applicat__0BE735C316236FA9");


            entity.ToTable("ApplicationChildMenu");

            entity.Property(e => e.Id).HasColumnName("ApplicationChildMenuId");
            entity.Property(e => e.ApplicationChildMenuIcon)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.ApplicationChildMenuIcon2).HasMaxLength(500);
            entity.Property(e => e.ApplicationChildMenuLink)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.ApplicationChildMenuName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ApplicationMenuId);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedDate);
            entity.Property(e => e.IsActive);
            entity.Property(e => e.ModifiedBy).HasMaxLength(100);
            entity.Property(e => e.ModifiedDate);
            entity.Property(e => e.Sequence);

            entity.HasOne(d => d.ApplicationMenu).WithMany(p => p.ApplicationChildMenus)
                .HasForeignKey(d => d.ApplicationMenuId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Applicati__Appli__567ED357");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ApplicationChildMenu> entity);
    }
}
