// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class ApplicationMenuConfiguration : IEntityTypeConfiguration<ApplicationMenu>
    {
        public void Configure(EntityTypeBuilder<ApplicationMenu> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Applicat__E37CD6C7CFC1C799");


            entity.ToTable("ApplicationMenu");

            entity.Property(e => e.Id).HasColumnName("ApplicationMenuId");
            entity.Property(e => e.ApplicationMenuIcon)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.ApplicationMenuIcon2).HasMaxLength(500);
            entity.Property(e => e.ApplicationMenuLink)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.ApplicationMenuName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedDate);
            entity.Property(e => e.IsActive);
            entity.Property(e => e.ModifiedBy).HasMaxLength(100);
            entity.Property(e => e.ModifiedDate);
            entity.Property(e => e.Sequence);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ApplicationMenu> entity);
    }
}
