// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class ApplicationFunctionalityConfiguration : IEntityTypeConfiguration<ApplicationFunctionality>
    {
        public void Configure(EntityTypeBuilder<ApplicationFunctionality> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Applicat__BDD9B3C4B3731912");


            entity.Property(e => e.Id).HasColumnName("ApplicationFunctionalityId");
            entity.Property(e => e.ApplicationChildMenuId);
            entity.Property(e => e.ApplicationMenuId);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedDate);
            entity.Property(e => e.Functionality)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.IsActive);
            entity.Property(e => e.ModifiedBy).HasMaxLength(100);
            entity.Property(e => e.ModifiedDate);

            entity.HasOne(d => d.ApplicationChildMenu).WithMany(p => p.ApplicationFunctionalities)
                .HasForeignKey(d => d.ApplicationChildMenuId)
                .HasConstraintName("FK__Applicati__Appli__58671BC9");

            entity.HasOne(d => d.ApplicationMenu).WithMany(p => p.ApplicationFunctionalities)
                .HasForeignKey(d => d.ApplicationMenuId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Applicati__Appli__5772F790");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ApplicationFunctionality> entity);
    }
}
