// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class CropInsuranceCategoryConfiguration : IEntityTypeConfiguration<CropInsuranceCategory>
    {
        public void Configure(EntityTypeBuilder<CropInsuranceCategory> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__CropInsu__19093A0B53ECEF8C");


            entity.ToTable("CropInsuranceCategory", tb => tb.HasTrigger("trg_cropinsurancecategory_update"));

            entity.Property(e => e.Id).HasColumnName("CategoryId");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CompanyId);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Company).WithMany(p => p.CropInsuranceCategories)
                .HasForeignKey(d => d.CompanyId)
                .HasConstraintName("FK__CropInsur__Compa__04459E07");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CropInsuranceCategory> entity);
    }
}
