// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class CropsAuConfiguration : IEntityTypeConfiguration<CropsAu>
    {
        public void Configure(EntityTypeBuilder<CropsAu> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Crops_AU__5F389638E1FA4A86");


            entity.ToTable("Crops_AU");

            entity.Property(e => e.Id).HasColumnName("HistoryRowId");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.CropCategoryId);
            entity.Property(e => e.CropId);
            entity.Property(e => e.CropName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.HistoryCreatedDate).HasColumnType("datetime");
            entity.Property(e => e.IsActive);
            entity.Property(e => e.MinOrderQuantity).HasColumnType("decimal(11, 2)");
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.QuantityUnits).HasDefaultValue(1);
            entity.Property(e => e.SequenceId);

            entity.HasOne(d => d.CropCategory).WithMany(p => p.CropsAus)
                .HasForeignKey(d => d.CropCategoryId)
                .HasConstraintName("FK__Crops_AU__CropCa__3B0BC30C");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CropsAu> entity);
    }
}
