// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class CropConfiguration : IEntityTypeConfiguration<Crop>
    {
        public void Configure(EntityTypeBuilder<Crop> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Crops__92356115E929DB23");


            entity.ToTable(tb => tb.HasTrigger("trigger_Crops_AU"));

            entity.Property(e => e.Id).HasColumnName("CropId");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.CropCategoryId);
            entity.Property(e => e.CropName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.IsActive);
            entity.Property(e => e.MinOrderQuantity).HasColumnType("decimal(11, 2)");
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.QuantityUnits).HasDefaultValue(1);
            entity.Property(e => e.SequenceId);

            entity.HasOne(d => d.CropCategory).WithMany(p => p.Crops)
                .HasForeignKey(d => d.CropCategoryId)
                .HasConstraintName("FK__Crops__CropCateg__36470DEF");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Crop> entity);
    }
}
