// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class CropInsuranceAuConfiguration : IEntityTypeConfiguration<CropInsuranceAu>
    {
        public void Configure(EntityTypeBuilder<CropInsuranceAu> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__CropInsu__5F389638B262D123");


            entity.ToTable("CropInsurance_AU");

            entity.Property(e => e.Id).HasColumnName("HistoryRowId");
            entity.Property(e => e.Comments)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.CropInsuranceId);
            entity.Property(e => e.CropName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FarmerCropId);
            entity.Property(e => e.FarmerId);
            entity.Property(e => e.HistoryCreatedDate).HasColumnType("datetime");
            entity.Property(e => e.InsurancePolicyId);
            entity.Property(e => e.InsuranceRiskId);
            entity.Property(e => e.IsActive);
            entity.Property(e => e.Latitude).HasColumnType("decimal(8, 6)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.FarmerCrop).WithMany(p => p.CropInsuranceAus)
                .HasForeignKey(d => d.FarmerCropId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FarmerCrops_CropInsurance_AU");

            entity.HasOne(d => d.Farmer).WithMany(p => p.CropInsuranceAus)
                .HasForeignKey(d => d.FarmerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Farmers_CropInsurance_AU");

            entity.HasOne(d => d.InsurancePolicy).WithMany(p => p.CropInsuranceAus)
                .HasForeignKey(d => d.InsurancePolicyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InsurancePolicies_CropInsurance_AU");

            entity.HasOne(d => d.InsuranceRisk).WithMany(p => p.CropInsuranceAus)
                .HasForeignKey(d => d.InsuranceRiskId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InsuranceRisk_CropInsurance_AU");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CropInsuranceAu> entity);
    }
}
