// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class FunctionalityApprovalProcessConfiguration : IEntityTypeConfiguration<FunctionalityApprovalProcess>
    {
        public void Configure(EntityTypeBuilder<FunctionalityApprovalProcess> entity)
        {
            entity.ToTable("FunctionalityApprovalProcess");

            entity.Property(e => e.Id).HasColumnName("FunctionalityApprovalProcessId");
            entity.Property(e => e.ApplicationFunctionalityId);
            entity.Property(e => e.ApprovalProcess)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedDate);
            entity.Property(e => e.IsActive);
            entity.Property(e => e.ModifiedBy).HasMaxLength(100);
            entity.Property(e => e.ModifiedDate);

            entity.HasOne(d => d.ApplicationFunctionality).WithMany(p => p.FunctionalityApprovalProcesses)
                .HasForeignKey(d => d.ApplicationFunctionalityId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FunctionalityApprovalProcess> entity);
    }
}
