// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class InsurancePolicyAuConfiguration : IEntityTypeConfiguration<InsurancePolicyAu>
    {
        public void Configure(EntityTypeBuilder<InsurancePolicyAu> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Insuranc__A17F23986DBA7219");


            entity.ToTable("InsurancePolicy_Au");

            entity.Property(e => e.Id).HasColumnName("AuditId");
            entity.Property(e => e.ActionTimestamp)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ActionType)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.CategoryId);
            entity.Property(e => e.CompanyId);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.InsurancePolicyId);
            entity.Property(e => e.IsActive);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PolicyName)
                .HasMaxLength(255)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InsurancePolicyAu> entity);
    }
}
