// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class InsurancePremiumPaymentConfiguration : IEntityTypeConfiguration<InsurancePremiumPayment>
    {
        public void Configure(EntityTypeBuilder<InsurancePremiumPayment> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__IPremiumP__679D297815A2DF98");
            entity.Property(e => e.Id).HasColumnName("PremiumPaymentId");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.CropInsuranceId);
            entity.Property(e => e.Currency)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.IsActive);
            entity.Property(e => e.ModeOfPayment)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.policyNumber)
                .HasMaxLength(100)
                .IsUnicode(false);
            
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PaidAmount).HasColumnType("money");
            entity.Property(e => e.PaymentDate).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TaxAmount).HasColumnType("money");
            entity.Property(e => e.TotalPaidAmount).HasColumnType("money");
            entity.HasOne(d => d.CropInsurance).WithMany(p => p.InsurancePremiumPayments)
                .HasForeignKey(d => d.CropInsuranceId)
                .HasConstraintName("FK__Insurance__CropI__5C02A283");
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InsurancePremiumPayment> entity);
    }
}
