// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class InsuranceProviderDocumentsAuConfiguration : IEntityTypeConfiguration<InsuranceProviderDocumentsAu>
    {
        public void Configure(EntityTypeBuilder<InsuranceProviderDocumentsAu> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Insuranc__5F389638AF17B6E4");


            entity.ToTable("InsuranceProviderDocuments_AU");

            entity.Property(e => e.Id).HasColumnName("HistoryRowId");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.DocumentName)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.DocumentPath).IsUnicode(false);
            entity.Property(e => e.HistoryCreatedDate).HasColumnType("datetime");
            entity.Property(e => e.InsuranceProviderDocumentId);
            entity.Property(e => e.InsurerId);
            entity.Property(e => e.IsActive);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Insurer).WithMany(p => p.InsuranceProviderDocumentsAus)
                .HasForeignKey(d => d.InsurerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InsuranceProviders_InsuranceProviderDocuments_AU");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InsuranceProviderDocumentsAu> entity);
    }
}
