// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class InsurancePremiumConfiguration : IEntityTypeConfiguration<InsurancePremium>
    {
        public void Configure(EntityTypeBuilder<InsurancePremium> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Insuranc__F95457D5C446FE53");


            entity.ToTable("InsurancePremium", tb => tb.HasTrigger("trigger_InsurancePremium_AU"));

            entity.Property(e => e.Id).HasColumnName("InsurancePremiumId");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.InsurancePolicyId);
            entity.Property(e => e.InsuranceRiskId);
            entity.Property(e => e.IsActive);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PremiumAmountCurrency).HasColumnType("money");
            entity.Property(e => e.SumInsuredAmount).HasColumnType("money");
            entity.Property(e => e.SumInsuredAmountCurrency).HasColumnType("money");
            entity.Property(e => e.TotalPremiumAmount).HasColumnType("money");

            entity.HasOne(d => d.InsurancePolicy).WithMany(p => p.InsurancePremia)
                .HasForeignKey(d => d.InsurancePolicyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InsurancePolicy_InsurancePremium");

            entity.HasOne(d => d.InsuranceRisk).WithMany(p => p.InsurancePremia)
                .HasForeignKey(d => d.InsuranceRiskId)
                .HasConstraintName("FK_InsuranceRisk_InsurancePremium");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InsurancePremium> entity);
    }
}
