// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class InsuranceRequestConfiguration : IEntityTypeConfiguration<InsuranceRequest>
    {
        public void Configure(EntityTypeBuilder<InsuranceRequest> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Insuranc__6E56996F64692F25");


            entity.Property(e => e.Id).HasColumnName("InsuranceRequestId");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.CropName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.FarmLocationDistrict)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.FarmLocationParish).HasMaxLength(200);
            entity.Property(e => e.FarmLocationSubCounty).HasMaxLength(200);
            entity.Property(e => e.FarmLocationVillage).HasMaxLength(200);
            entity.Property(e => e.FarmLocationWard).HasMaxLength(200);
            entity.Property(e => e.FarmerCropId);
            entity.Property(e => e.FarmerId);
            entity.Property(e => e.FarmerName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.HomeLocationDistrict)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.HomeLocationParish).HasMaxLength(200);
            entity.Property(e => e.HomeLocationSubCounty).HasMaxLength(200);
            entity.Property(e => e.HomeLocationVillage).HasMaxLength(200);
            entity.Property(e => e.HomeLocationWard).HasMaxLength(200);
            entity.Property(e => e.InsuranceCompanyName).HasMaxLength(500);
            entity.Property(e => e.IsActive);
            entity.Property(e => e.IsFarmLocationSameAsHomeLocation);
            entity.Property(e => e.IsRequestSubmitted);
            entity.Property(e => e.ModifiedBy).HasMaxLength(100);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.ProgramName).HasMaxLength(500);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InsuranceRequest> entity);
    }
}
