// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class InsurancePolicy1Configuration : IEntityTypeConfiguration<InsurancePolicy1>
    {
        public void Configure(EntityTypeBuilder<InsurancePolicy1> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Insuranc__8D74AD1F32569A1F");


            entity.ToTable("InsurancePolicy", tb => tb.HasTrigger("trg_insurancepolicy_update"));

            entity.Property(e => e.Id).HasColumnName("InsurancePolicyId");
            entity.Property(e => e.CategoryId);
            entity.Property(e => e.CompanyId);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PolicyName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.Category).WithMany(p => p.InsurancePolicy1s)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK__Insurance__Categ__090A5324");

            entity.HasOne(d => d.Company).WithMany(p => p.InsurancePolicy1s)
                .HasForeignKey(d => d.CompanyId)
                .HasConstraintName("FK__Insurance__Compa__08162EEB");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InsurancePolicy1> entity);
    }
}
