// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class MenuRolesFunctionalityConfiguration : IEntityTypeConfiguration<MenuRolesFunctionality>
    {
        public void Configure(EntityTypeBuilder<MenuRolesFunctionality> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__MenuRole__074CCD71B3141746");


            entity.Property(e => e.Id).HasColumnName("MenuRolesFunctionalityId");
            entity.Property(e => e.ApplicationFunctionalityId);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedDate);
            entity.Property(e => e.Enable);
            entity.Property(e => e.IsActive);
            entity.Property(e => e.ModifiedBy).HasMaxLength(100);
            entity.Property(e => e.ModifiedDate);
            entity.Property(e => e.RoleId);

            entity.HasOne(d => d.ApplicationFunctionality).WithMany(p => p.MenuRolesFunctionalities)
                .HasForeignKey(d => d.ApplicationFunctionalityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MenuRoles__Appli__5C37ACAD");

            entity.HasOne(d => d.Role).WithMany(p => p.MenuRolesFunctionalities)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MenuRoles__RoleI__5D2BD0E6");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MenuRolesFunctionality> entity);
    }
}
