// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class MenuRolesPrivilegeConfiguration : IEntityTypeConfiguration<MenuRolesPrivilege>
    {
        public void Configure(EntityTypeBuilder<MenuRolesPrivilege> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__MenuRole__FD265CFDD6BDBA7B");


            entity.Property(e => e.Id).HasColumnName("MenuRolesPrivilegeId");
            entity.Property(e => e.ApplicationChildMenuId);
            entity.Property(e => e.ApplicationMenuId);
            entity.Property(e => e.Create);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedDate);
            entity.Property(e => e.Delete);
            entity.Property(e => e.IsActive);
            entity.Property(e => e.ModifiedBy).HasMaxLength(100);
            entity.Property(e => e.ModifiedDate);
            entity.Property(e => e.Read);
            entity.Property(e => e.RoleId);
            entity.Property(e => e.Update);

            entity.HasOne(d => d.ApplicationChildMenu).WithMany(p => p.MenuRolesPrivileges)
                .HasForeignKey(d => d.ApplicationChildMenuId)
                .HasConstraintName("FK__MenuRoles__Appli__5F141958");

            entity.HasOne(d => d.ApplicationMenu).WithMany(p => p.MenuRolesPrivileges)
                .HasForeignKey(d => d.ApplicationMenuId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MenuRoles__Appli__5E1FF51F");

            entity.HasOne(d => d.Role).WithMany(p => p.MenuRolesPrivileges)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MenuRoles__RoleI__60083D91");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MenuRolesPrivilege> entity);
    }
}
