// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class MenuRoleFunctionalityApprovalProcessConfiguration : IEntityTypeConfiguration<MenuRoleFunctionalityApprovalProcess>
    {
        public void Configure(EntityTypeBuilder<MenuRoleFunctionalityApprovalProcess> entity)
        {
            entity.ToTable("MenuRoleFunctionalityApprovalProcess");

            entity.Property(e => e.Id).HasColumnName("MenuRoleFunctionalityApprovalProcessId");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedDate);
            entity.Property(e => e.Enable);
            entity.Property(e => e.FunctionalityApprovalProcessId);
            entity.Property(e => e.IsActive);
            entity.Property(e => e.ModifiedBy).HasMaxLength(100);
            entity.Property(e => e.ModifiedDate);
            entity.Property(e => e.RoleId);

            entity.HasOne(d => d.FunctionalityApprovalProcess).WithMany(p => p.MenuRoleFunctionalityApprovalProcesses)
                .HasForeignKey(d => d.FunctionalityApprovalProcessId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Role).WithMany(p => p.MenuRoleFunctionalityApprovalProcesses).HasForeignKey(d => d.RoleId);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MenuRoleFunctionalityApprovalProcess> entity);
    }
}
