// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class PaymentModeConfiguration : IEntityTypeConfiguration<PaymentMode>
    {
        public void Configure(EntityTypeBuilder<PaymentMode> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__PaymentM__F9599549EA41D054");


            entity.ToTable(tb => tb.HasTrigger("trigger_PaymentModes_AU"));

            entity.Property(e => e.Id).HasColumnName("PaymentModeId");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.IsActive);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PaymentMode1)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("PaymentMode");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PaymentMode> entity);
    }
}
