// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class PremiumPaymentsAuConfiguration : IEntityTypeConfiguration<PremiumPaymentsAu>
    {
        public void Configure(EntityTypeBuilder<PremiumPaymentsAu> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__PremiumP__5F38963879046800");


            entity.ToTable("PremiumPayments_AU");

            entity.Property(e => e.Id).HasColumnName("HistoryRowId");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.CropInsuranceId);
            entity.Property(e => e.CropInsurancePremiumId);
            entity.Property(e => e.Currency)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.HistoryCreatedDate).HasColumnType("datetime");
            entity.Property(e => e.IsActive);
            entity.Property(e => e.ModeOfPayment)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PaidAmount).HasColumnType("money");
            entity.Property(e => e.PaymentDate).HasColumnType("datetime");
            entity.Property(e => e.PremiumPaymentId);
            entity.Property(e => e.Status)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TaxAmount).HasColumnType("money");
            entity.Property(e => e.TotalPaidAmount).HasColumnType("money");

            entity.HasOne(d => d.CropInsurance).WithMany(p => p.PremiumPaymentsAus)
                .HasForeignKey(d => d.CropInsuranceId)
                .HasConstraintName("FK_CropInsurance_PremiumPayments_AU");

            entity.HasOne(d => d.CropInsurancePremium).WithMany(p => p.PremiumPaymentsAus)
                .HasForeignKey(d => d.CropInsurancePremiumId)
                .HasConstraintName("FK_CropInsurancePremiums_PremiumPayments_AU");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PremiumPaymentsAu> entity);
    }
}
