// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class ProgramConfiguration : IEntityTypeConfiguration<Program>
    {
        public void Configure(EntityTypeBuilder<Program> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Programs__752560587B88440F");


            entity.Property(e => e.Id).HasColumnName("ProgramId");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.DistrictId);
            entity.Property(e => e.IsActive);
            entity.Property(e => e.ModifiedBy).HasMaxLength(100);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.ParishId);
            entity.Property(e => e.ProgramName)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.RegionId);
            entity.Property(e => e.SubCountyId);

            entity.HasOne(d => d.District).WithMany(p => p.Programs).HasForeignKey(d => d.DistrictId);

            entity.HasOne(d => d.Parish).WithMany(p => p.Programs).HasForeignKey(d => d.ParishId);

            entity.HasOne(d => d.Region).WithMany(p => p.Programs)
                .HasForeignKey(d => d.RegionId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.SubCounty).WithMany(p => p.Programs).HasForeignKey(d => d.SubCountyId);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Program> entity);
    }
}
