// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class SeasonCutOffDateConfiguration : IEntityTypeConfiguration<SeasonCutOffDate>
    {
        public void Configure(EntityTypeBuilder<SeasonCutOffDate> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__SeasonCu__8CC0AA5F20ECD371");


            entity.Property(e => e.Id).HasColumnName("SeasonCutOffDateId");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.CropCategoryId);
            entity.Property(e => e.CropId);
            entity.Property(e => e.EndDate);
            entity.Property(e => e.IsActive);
            entity.Property(e => e.ModifiedBy).HasMaxLength(100);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.RegionId);
            entity.Property(e => e.SeasonId);
            entity.Property(e => e.StartDate);

            entity.HasOne(d => d.CropCategory).WithMany(p => p.SeasonCutOffDates).HasForeignKey(d => d.CropCategoryId);

            entity.HasOne(d => d.Crop).WithMany(p => p.SeasonCutOffDates).HasForeignKey(d => d.CropId);

            entity.HasOne(d => d.Region).WithMany(p => p.SeasonCutOffDates)
                .HasForeignKey(d => d.RegionId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Season).WithMany(p => p.SeasonCutOffDates)
                .HasForeignKey(d => d.SeasonId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SeasonCutOffDate> entity);
    }
}
