// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class SubFunctionalityConfiguration : IEntityTypeConfiguration<SubFunctionality>
    {
        public void Configure(EntityTypeBuilder<SubFunctionality> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__SubFunct__BFAB7EFF988FD313");


            entity.ToTable(tb => tb.HasTrigger("trigger_SubFunctionalities_AU"));

            entity.Property(e => e.Id).HasColumnName("SubFunctionalityId");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.FunctionalityId);
            entity.Property(e => e.IsActive);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.SubFunctionality1)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("SubFunctionality");

            entity.HasOne(d => d.Functionality).WithMany(p => p.SubFunctionalities)
                .HasForeignKey(d => d.FunctionalityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Functionalities");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SubFunctionality> entity);
    }
}
