// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class SubFunctionalitiesAuConfiguration : IEntityTypeConfiguration<SubFunctionalitiesAu>
    {
        public void Configure(EntityTypeBuilder<SubFunctionalitiesAu> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__SubFunct__5F3896385A9B63AB");


            entity.ToTable("SubFunctionalities_AU");

            entity.Property(e => e.Id).HasColumnName("HistoryRowId");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.FunctionalityId);
            entity.Property(e => e.HistoryCreatedDate).HasColumnType("datetime");
            entity.Property(e => e.IsActive);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.SubFunctionality)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.SubFunctionalityId);

            entity.HasOne(d => d.Functionality).WithMany(p => p.SubFunctionalitiesAus)
                .HasForeignKey(d => d.FunctionalityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Functionalities_AU");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SubFunctionalitiesAu> entity);
    }
}
