// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class TaxComponentConfiguration : IEntityTypeConfiguration<TaxComponent>
    {
        public void Configure(EntityTypeBuilder<TaxComponent> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__TaxCompo__E333E7C11587A132");


            entity.ToTable(tb => tb.HasTrigger("trigger_TaxComponents_AU"));

            entity.Property(e => e.Id).HasColumnName("TaxComponentId");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.IsActive);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.TaxComponent1)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("TaxComponent");
            entity.Property(e => e.Value);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TaxComponent> entity);
    }
}
