// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain;
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eSusInsurers.Domain.Configurations
{
    public partial class TaxComponentsAuConfiguration : IEntityTypeConfiguration<TaxComponentsAu>
    {
        public void Configure(EntityTypeBuilder<TaxComponentsAu> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__TaxCompo__5F3896381C36D00C");


            entity.ToTable("TaxComponents_AU");

            entity.Property(e => e.Id).HasColumnName("HistoryRowId");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.HistoryCreatedDate).HasColumnType("datetime");
            entity.Property(e => e.IsActive);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.TaxComponent)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TaxComponentId);
            entity.Property(e => e.Value);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TaxComponentsAu> entity);
    }
}
